### ISSUE TITLE
大佬能专门写个 gradle 构建的 android jni 的demo 么.

### ISSUE THREAD

**Issue by yizems** [enbandari/hello-kni#2]
你的demo native 部分(prebuiltLibrary)不是用的 gradle 构建的, 我最近试了很多方法,始终无法构建出来能够调用jni 的 项目,非常感谢

小白一枚,嗷嗷待教中=.=

**Comment by bennyhuo** [comment]
印象中 kn 没有对 Android 的 Jni 提供很好的 gradle 支持，技术方案选取的时候最好先避免。

**Comment by bennyhuo** [comment]
也许我可以弄一个 mpp 的工程

**Comment by bennyhuo** [comment]
好了，搞定：[mpp-gradle](https://github.com/enbandari/hello-kni/tree/mpp-gradle)

Readme 还没顾上写，不过应该比较简单
