### ISSUE TITLE
没有代码提示

### ISSUE THREAD

**Issue by yizems** [enbandari/hello-kni#3]
使用 AS3.6 和 Idea 2019.3 版本, 没有代码提示, 这个是我的软件版本太低的原因么

**Comment by bennyhuo** [comment]
具体是什么代码没有提示。。。。

--------------原始邮件--------------
发件人："YiZe "<notifications@github.com&gt;;
发送时间：2020年5月16日(星期六) 晚上6:02
收件人："enbandari/hello-kni" <hello-kni@noreply.github.com&gt;;
抄送："Subscribed "<subscribed@noreply.github.com&gt;;
主题：[enbandari/hello-kni] 没有代码提示 (#3)
-----------------------------------

 

 
使用 AS3.6 和 Idea 2019.3 版本, 没有代码提示, 这个是我的软件版本太低的原因么

**Comment by yizems** [comment]
![image](https://user-images.githubusercontent.com/16949474/82119086-3ce58580-97ae-11ea-83a9-2496b21ade64.png)


![image](https://user-images.githubusercontent.com/16949474/82119093-4373fd00-97ae-11ea-84a3-35b50728efb1.png)

![image](https://user-images.githubusercontent.com/16949474/82119099-4d95fb80-97ae-11ea-9a83-f350ff2f0ec3.png)


这个函数,输入的时候也没有提示,我在 AS 中会直接爆红

![image](https://user-images.githubusercontent.com/16949474/82119122-8afa8900-97ae-11ea-9b06-1d4fcff325c1.png)


我怀疑跟这个有关系

![image](https://user-images.githubusercontent.com/16949474/82119211-415e6e00-97af-11ea-999f-0fa98dd93ebe.png)

**Comment by yizems** [comment]
我解决了这个问题, 需要kotlin 1.3.72 , 我疏忽了

目前kotlin 1.3.72 插件需要 AS 4.0 RC1 和 idea 2020 版本
