### ISSUE TITLE
JNI_OnLoad方法必须写么?

### ISSUE THREAD

**Issue by yizems** [enbandari/hello-kni#4]
https://github.com/enbandari/hello-kni/blob/d4c86bb7fc68a303e9bc98b2a0046fea1f7e1913/nativeLib/src/androidNativeArm32Main/kotlin/main.kt#L32

我看您 在代码中是用到了 动态注册, 如果不适用动态注册,是否可以不用写 `JNI_OnLoad`方法

**Comment by bennyhuo** [comment]
可以不用写

--------------原始邮件--------------
发件人："YiZe "<notifications@github.com&gt;;
发送时间：2020年6月10日(星期三) 下午2:19
收件人："enbandari/hello-kni" <hello-kni@noreply.github.com&gt;;
抄送："Subscribed "<subscribed@noreply.github.com&gt;;
主题：[enbandari/hello-kni] JNI_OnLoad方法必须写么? (#4)
-----------------------------------

 

 
https://github.com/enbandari/hello-kni/blob/d4c86bb7fc68a303e9bc98b2a0046fea1f7e1913/nativeLib/src/androidNativeArm32Main/kotlin/main.kt#L32
 
我看您 在代码中是用到了 动态注册, 如果不适用动态注册,是否可以不用写 JNI_OnLoad方法

**Comment by yizems** [comment]
非常感谢大佬的项目,之前一直关注来着, 总算是完成了第一个 kotlin native jni 的程序,已用于项目中的数据加密处理,真的非常感谢

**Comment by bennyhuo** [comment]
666～

--------------原始邮件--------------
发件人："YiZe "<notifications@github.com&gt;;
发送时间：2020年6月11日(星期四) 晚上8:10
收件人："enbandari/hello-kni" <hello-kni@noreply.github.com&gt;;
抄送："Bennyhuo "<bennyhuo@kotliner.cn&gt;;"Comment "<comment@noreply.github.com&gt;;
主题：Re: [enbandari/hello-kni] JNI_OnLoad方法必须写么? (#4)
-----------------------------------

 

 
非常感谢大佬的项目,之前一直关注来着, 总算是完成了第一个 kotlin native jni 的程序,已用于项目中的数据加密处理,真的非常感谢
